Merge remote-tracking branch 'origin/main' into RuggeroVisintin/issue57/1

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,3 +2,25 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npx commitlint --edit
+warnings=$(npx spellchecker -f $1 | grep 'warning')
+
+# echo all warnings
+if (( "${#warnings[@]}" > 0 )); then
+  printf "%s\n" "[commit-msg hook] Possible spelling errors found in commit message:" "${warnings[@]}"
+fi
+
+f [ -t 1 ]; then
+  exec < /dev/tty
+
+  while true; do
+    read -p "[commit-msg hook] Proceed anyway? (y/n) " yn
+    if [ "$yn" = "" ]; then
+      yn='y'
+    fi
+    case $yn in
+        [Yy] ) break;;
+        [Nn] ) exit 1;;
+        * ) echo "Please answer y for yes or n for no.";;
+    esac
+  done
+fi
