ci: update pre-push script

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,15 @@
 set -e
 
-npm run lint
+# run as if we were in the pipeline
+CI=true && npm run lint
 
-read -p "Continue? (Y/N): " confirm [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1
+if [ "$(which "$read")" == "" ]; then
+  echo "Cannot read input, please run git push again from another shell">&2
+  exit 1
+fi
 
-"Confirmed, continuing with push..."
+read -p "Continue? (Y/N): " confirm
 
-exit 1
+if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
+  echo "Confirmed, continuing with push..."
+fi
