ci: warn when lint fails with errors on pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,25 +1,5 @@
 set -e
 
-if [ -t 0 ]; then
-    echo running interactively>&2
-fi
-
 npm run lint || {
-    echo "Linting failed with errors" >&2
-
-    if [ "$(which "read")" == "" ]; then
-        echo "Cannot read input, please run git push again from another shell">&2
-        exit 1
-    fi
-
-    read -p "Continue? (Y/N): " confirm
-
-    if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
-        echo "Confirmed, continuing with push...">&2
-    else 
-        echo "Aborting push...">&2
-        exit 1
-    fi
+    echo "[warning] Linting failed with errors" >&2
 }
-
-exit 1;
