ci: add broken build warning in git hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,9 @@
 set -e
 
-npm run lint:fix || true
+npm run lint:fix || {
+    echo "[warning] Linting failed with errors" >&2
+}
+
+npm run build || {
+    echo "[warning] Build failed" >&2
+}
